version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6.30-cli
     steps:
      - checkout
      - run:
          name: Running Tests
          command: echo "No Tests to Run."
   deploy:
     docker:
       - image: circleci/php:5.6.30-cli
     steps:
      - add_ssh_keys:
          fingerprints:
           - "41:9e:a5:28:11:2c:9b:8d:36:01:07:11:8c:cf:29:fe"
      - run:
          name: Clearing known_hosts
          command: ssh-keygen -R itan.io

      - deploy:
          name: Deploy if tests pass and branch is Master
          command: |
            echo 'itan.io ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjxhmapjerbN9NNKujykJJcBIoY++lVueeaxNDMIllnf/NdRIFMnISwe1KbUrbttpRGIO92aMAb7/YJswlJdlW2beufnQcTX4h7cLKQucZfCtkl8cDXk4/BU/oJRZjxIgnciAJu5OocRVJw4Xf1fe9K2hL3q5HzTm1m6y+9pPi4wFYvwHQhZySBAIoLBj9hEbxq7Z4vv1EiKc5dNrn0Xvgb3eJoeNgnSv5+m7smJLE/oAgXnEaO2EsqeqtD14zSIXoqP7CuyXqLk5xv6Zj98neTl6rZUX5j0icQPwLWKODVjetRYyglr4rpBafPkwLGAdboqw1y936kBi3bnL4y9Sj itanio@james-wilson' >> ~/.ssh/known_hosts
            scp -oStrictHostKeyChecking=no -r ~/project/ itanio@itan.io:/home/itanio/itan.io/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master