version: 2
jobs:
   build-job:
     docker:
       - image: circleci/php:5.6.30-cli
     steps:
       - checkout
       - run: 
        name: Running Tests
        command: echo "No Tests to Run."
  
  deploy-job:
     docker:
       - image: circleci/php:5.6.30-cli
     steps:
      -run:
        name: Deploy if tests pass and branch is Master
        command: scp -r * itanio@itan.io:/home/itanio/itan.io/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
       